
name: Pull Request events
run-name: ${{ github.actor }} pushed to PR
on:
  - pull_request
jobs:
  linters-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run tox
        run: |
          pip install tox
          tox run -e 3.12 -- check_lint
  run-uts-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tox
        run: |
          pip install tox
          tox -e ${{ matrix.python-version }}
